on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "Deploying to production..."
              wrangler pages deploy ./dist --project-name=dl --production
            else
              echo "Deploying to preview..."
              wrangler pages deploy ./dist --project-name=dl --branch=develop
            fi
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
