on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm install && npm run build

      - name: Install Wrangler 4 
        run: npm install --save-dev wrangler@4

      - name: Calculate compatibility date
        run: echo "DEPLOY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --assets ./dist --name=dl --compatibility-date=${{ env.DEPLOY_DATE }} --preview | grep -o "https://[^ ]*workers.dev" | head -n 1)
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
